---
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskapp"
  DATABASE_USER: "taskapp_user"