---
apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
  namespace: taskapp
type: Opaque
stringData:
  DATABASE_PASSWORD: "taskapp_password"
  SECRET_KEY: "capstone-phoenix-secret-key-2026"
  DATABASE_URL: "postgresql://taskapp_user:taskapp_password@postgres:5432/taskapp"