[server]
control-plane ansible_host=51.21.244.36 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/task-app.pem

[agents]
worker-1 ansible_host=13.62.18.251 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/task-app.pem
worker-2 ansible_host=13.49.245.87 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/task-app.pem

[k3s_cluster:children]
server
agents