[server]
control-plane ansible_host=13.60.90.137 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/task-app.pem

[agents]
worker-1 ansible_host=13.49.21.52 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/task-app.pem
worker-2 ansible_host=51.20.109.222 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/task-app.pem

[k3s_cluster:children]
server
agents