---
- name: Harden all nodes
  hosts: k3s_cluster
  become: yes
  roles:
    - hardening

- name: Set up k3s control plane
  hosts: server
  become: yes
  roles:
    - k3s-server

- name: Join worker nodes to cluster
  hosts: agents
  become: yes
  roles:
    - k3s-agent