---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zinnyrosy/capstone-phoenix.git
    targetRevision: feature/terraform
    path: manifests/taskapp
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true